### ISSUE TITLE
Support and test /dns/

### ISSUE THREAD

**Issue by lidel** [multiformats/go-multiaddr-dns#47]
It seems that this library supports `/dns4` and `/dns6` but  does not support `/dns`

Given that 
- JS https://github.com/multiformats/js-multiaddr/pull/253 is adding support for `/dns/` 
- and it is a valid code present in both [multiaddr/protocols.csv](https://github.com/multiformats/multiaddr/blob/master/protocols.csv) and [multicodec/table.csv](https://github.com/multiformats/multicodec/blob/master/table.csv)

i think we should add it here as well.

## Resolution order

Reuse prior art from https://en.wikipedia.org/wiki/Happy_Eyeballs  ?

**Comment by lidel** [comment]
@schomatis is this something you'd be interested in adding to your queue?

**Comment by schomatis** [comment]
Adding it to queue (but haven't seen it in depth), anyone in the community is welcome to take a look at this issue in the meanwhile but please flag it here.

**Comment by schomatis** [comment]
Reading the code now.

Officially assigning this to me now (though I don't have triage permissions here to mark it on the issue). If someone is working on this please flag it now.

**Comment by schomatis** [comment]
@lidel Reading the code, we seem to support the `/dns/` protocol:

https://github.com/multiformats/go-multiaddr-dns/blob/0bad63ddb983cf7824f45f1490f81f3b3b66fe62/resolve.go#L150-L191

```bash
$ madns /dns6/example.com
/ip6/2606:2800:220:1:248:1893:25c8:1946

$ madns /dns4/example.com
/ip4/93.184.216.34

$ madns /dns/example.com
/ip4/93.184.216.34
/ip6/2606:2800:220:1:248:1893:25c8:1946
```

---------------------

Could you first confirm if the above is what you were requesting? If it is then we can talk some extra documentation (`madns /dns/example.com` is not part of the command example) and testing, but I need to know first if I'm understanding the issue correctly (I'm new in IPFS/DNS world).

**Comment by schomatis** [comment]
(just a guess) Maybe we were experience problems because of:

https://github.com/multiformats/go-multiaddr-dns/blob/0bad63ddb983cf7824f45f1490f81f3b3b66fe62/resolve.go#L157-L160

**Comment by lidel** [comment]
@schomatis i think the bug was caused by the line fixed here: https://github.com/libp2p/go-libp2p/pull/1612/files#diff-8a203f70505b8dae3ee69421aa2326392c2f301091f557e44649fa40205f246fR26

With Kubo 0.14 (which uses go-libp2p with the above fix) I was able to connect to `/dns` just fine:

```console
$ ipfs swarm connect /dns/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A
connect 12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A success
```

Can you validate my assumptions here? If so, I think we can close this, right?

**Comment by schomatis** [comment]
> the bug was caused by

I'm still not sure what's the original bug being referenced here. I get the general issue but I have the impression there was an issue downstream that motivated this which I'm missing (it could be some of the background you listed which I didn't review in depth).

> `ipfs swarm connect /dns/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A`

Yes, this works for me (I have 0.15).

**Comment by lidel** [comment]
The original one is  https://github.com/libp2p/go-libp2p-relay-daemon/issues/18 – Kubo 0.12 failed to connect to `/wss` + `/dns` relays:
```console
$ ipfs swarm connect /dns/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A
error: connect 12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A failure: no good addresses
```

Since `/dns` handling got fixed, Kubo 0.14 connects  fine:
```console
$ ipfs swarm connect /dns/ipfs.thedisco.zone/tcp/4430/wss/p2p/12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A
connect 12D3KooWCyiHXACQpZxnvLTHXjFcFPPv69qPrX6svgdcmREZuS8A success
```

**Comment by schomatis** [comment]
Yes, makes sense, closing.

**Comment by schomatis** [comment]
(@lidel sorry, this is not in ipfs, you'll need to pull the lever)
